name: Triggered Workflow

on:
  repository_dispatch:
    types:
      - trigger-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add other steps as needed for your workflow
